github action for black linting checked added
community-phone-company/shipbob-sdk-python pull request #12
Opened 2022-11-18 12:13 UTC by shaharyar-shamshi

2022-11-18 12:15 UTC, lullis requested changes

2022-11-18 12:47 UTC, shaharyar-shamshi commented on requirements.txt
> +black==22.10.0
@lullis  fixed. I have added proper action and tested it as well

2022-11-18 12:52 UTC, shaharyar-shamshi commented
@lullis  should I add branch as well to trigger the action

2022-11-22 13:07 UTC, lullis approved these changes

2022-11-25 20:13 UTC, lullis commented
@shaharyar-shamshi , you need to sign your commit in order for it to be merged.

2022-11-26 12:19 UTC, shaharyar-shamshi commented
@lullis done

2022-12-11 03:18 UTC, lullis approved these changes

2022-12-11 03:22 UTC, merged